package db

import "go.mongodb.org/mongo-driver/bson"

// AddRate generate mongodb request for adding rate
func AddRate(rateName string) bson.A {
	return bson.A{
		bson.D{
			{"$set",
				bson.D{
					{"Rating." + rateName,
						bson.D{
							{"$sum",
								bson.A{
									"$Rating." + rateName,
									1,
								},
							},
						},
					},
				},
			},
		},
		bson.D{
			{"$set",
				bson.D{
					{"Rating.Average",
						bson.D{
							{"$divide",
								bson.A{
									bson.D{
										{"$sum",
											bson.A{
												bson.D{
													{"$multiply",
														bson.A{
															"$Rating.Five",
															5,
														},
													},
												},
												bson.D{
													{"$multiply",
														bson.A{
															"$Rating.Four",
															4,
														},
													},
												},
												bson.D{
													{"$multiply",
														bson.A{
															"$Rating.Three",
															3,
														},
													},
												},
												bson.D{
													{"$multiply",
														bson.A{
															"$Rating.Two",
															2,
														},
													},
												},
												bson.D{
													{"$multiply",
														bson.A{
															"$Rating.One",
															1,
														},
													},
												},
											},
										},
									},
									bson.D{
										{"$sum",
											bson.A{
												"$Rating.Five",
												"$Rating.Four",
												"$Rating.Three",
												"$Rating.Two",
												"$Rating.One",
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
	}
}

// ChangeRating generate mongodb request for changing rate
func ChangeRating1(from string, to string) bson.A {
	return bson.A{
		bson.D{
			{"$set",
				bson.D{
					{"Rating." + from,
						bson.D{
							{"$sum",
								bson.A{
									"$Rating." + from,
									-1,
								},
							},
						},
					},
					{"Rating." + to,
						bson.D{
							{"$sum",
								bson.A{
									"$Rating." + to,
									1,
								},
							},
						},
					},
				},
			},
		},
		bson.D{
			{"$set",
				bson.D{
					{"Rating.Average",
						bson.D{
							{"$divide",
								bson.A{
									bson.D{
										{"$sum",
											bson.A{
												bson.D{
													{"$multiply",
														bson.A{
															"$Rating.Five",
															5,
														},
													},
												},
												bson.D{
													{"$multiply",
														bson.A{
															"$Rating.Four",
															4,
														},
													},
												},
												bson.D{
													{"$multiply",
														bson.A{
															"$Rating.Three",
															3,
														},
													},
												},
												bson.D{
													{"$multiply",
														bson.A{
															"$Rating.Two",
															2,
														},
													},
												},
												bson.D{
													{"$multiply",
														bson.A{
															"$Rating.One",
															1,
														},
													},
												},
											},
										},
									},
									bson.D{
										{"$sum",
											bson.A{
												"$Rating.Five",
												"$Rating.Four",
												"$Rating.Three",
												"$Rating.Two",
												"$Rating.One",
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
	}
}
